version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "usefulness"
  - package-ecosystem: "gradle"
    directory: "buildSrc"
    schedule:
      interval: "daily"
    assignees:
      - "usefulness"
  - package-ecosystem: "gradle"
    directory: "sample"
    schedule:
      interval: "daily"
    assignees:
      - "usefulness"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "usefulness"
