name: Build project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/*.kt') }}
          restore-keys: |
            gradle-
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Code style check
        run: ./gradlew projectCodestyle
      - name: Assemble
        run: ./gradlew assemble
      - name: Unit tests
        run: ./gradlew projectCoverage
      - uses: codecov/codecov-action@v1
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: "${{ github.workspace }}/**/build/reports/tests"
      - name: Upload jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: "${{ github.workspace }}/**/build/reports/jacoco"

  build-all-sample-apps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle: [ 6.1.1, 6.5.1, 6.6-rc-4 ]
    name: Run with Gradle ${{ matrix.gradle }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/*.kt') }}
          restore-keys: |
            gradle-
      - name: Pre-compile plugin
        run: ./gradlew publishToMavenLocal -PuseMavenLocal
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: sample
          arguments: projectCode
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: sample
          gradle-version: ${{ matrix.gradle }}
          arguments: assemble
