name: Build project

on:
  push:

jobs:
  testing_things:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: docker build -t android:test .

      - run: docker run --rm -v `pwd`:/project  android:test bash -c 'cd /project; ./gradlew test --stacktrace'

      - run: "sudo find ~ -type d -user root -exec sudo chown -R $USER: {} +"
        if: ${{ always() }}

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: "${{ github.workspace }}/**/build/reports/tests"
